var players=['virat','rahul','sachin'];
var numbers=[];
var fruits=['apple','water melon','jackfruit','banana'];
console.log(typeof players);
console.log(players.length);
console.log(numbers.length);
console.log('players',players);
console.log(players.push('dhoni'));
console.log(players);
console.log(players.unshift('shewag'));
console.log('fruits',fruits);
console.log(fruits.pop());
console.log(fruits);
console.log(fruits.shift());
console.log(fruits);
var numbers=[1,2,3];
console.log(typeof numbers);