var n1=10;
var n2=12.5;
var n3=16.6;
console.log(n1);
console.log(n2);
console.log(typeof n1);
console.log(typeof n2);
console.log(Math.round(n2));
console.log(Math.round(n3));
console.log("n2",n2);
console.log("n3",n3);
console.log(Math.pow(2,3));
console.log(Math.sqrt(9));
var a1=12.4;
var a2=19.6;
console.log(Math.ceil(a1));
console.log(Math.round(a1));
console.log(Math.round(a2));
console.log(Math.floor(a2));
console.log(Math.max(11,9,45,15));
console.log(Math.min(11,9,45,15));
console.log(Math.random());
